export function buildTerminalWorkspaceVm(parts: Record<string, any>) {
  return {
    focusTerminal: parts.focusTerminal,
    terminalModeLabel: parts.terminalModeLabel,
    terminalTargetLabel: parts.terminalTargetLabel,
    activeTerminalMode: parts.activeTerminalMode,
    sshTabs: parts.sshTabs,
    sshSessionId: parts.sshSessionId,
    terminalEncoding: parts.terminalEncoding,
    terminalSnippetId: parts.terminalSnippetId,
    terminalSnippetCategory: parts.terminalSnippetCategory,
    terminalSnippetCategories: parts.terminalSnippetCategories,
    terminalSnippetItems: parts.terminalSnippetItems,
    snippetRunning: parts.snippetRunning,
    snippetKeyword: parts.snippetKeyword,
    switchSshTab: parts.switchSshTab,
    createSshTab: parts.createSshTab,
    handleSshTabClose: parts.handleSshTabClose,
    selectAllTerminal: parts.selectAllTerminal,
    copyTerminalSelection: parts.copyTerminalSelection,
    pasteToTerminal: parts.pasteToTerminal,
    runTerminalSnippet: parts.runTerminalSnippet,
    sendSnippetRawToTerminal: parts.sendSnippetRawToTerminal,
    closeSerial: parts.closeSerial,
    openTerminalContextMenu: parts.openTerminalContextMenu,
    snippetCommandLines: parts.snippetCommandLines,
    bindTermEl: parts.bindTermEl,
    exitTerminalView: parts.exitTerminalView,
    openSnippetsPanel: parts.openSnippetsPanel,
    openSshConnectionChooser: parts.openSshConnectionChooser,
  }
}
